version: "3.6"

services:

  api:
    build:
      context: .
      target: api
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8888", "--reload"]
    ports:
      - 8888:8888
    volumes:
      - ./services/trends/:/code/trends
    environment:
      - JWT_SECRET=secret
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/cofilm
    depends_on:
      - postgres

  tiktok-worker:
    build:
      context: .
      target: tiktok-worker
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." -- python -u main.py
    volumes:
      - ./workers/tiktok:/code/tiktok
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/cofilm
    depends_on:
      - postgres


  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8080:8080"
    volumes:
      - ./openapi:/openapi
    environment:
      SWAGGER_JSON: /openapi/openapi.json
    depends_on:
      - api

  postgres:
    image: postgres:14-alpine
    ports:
      - 6500:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cofilm

volumes:
  postgres:

networks:
  default:
    driver: bridge
    name: cofilm-net
